apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: infra-random-pod-memory-hog-1681732024
  namespace: litmus
  labels:
    subject: infra-random-pod-memory-hog_litmus
spec:
  schedule: 0 12 * * 0-6
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments:
      parameters:
        - name: adminModeNamespace
          value: litmus
    entrypoint: custom-chaos
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
    serviceAccountName: argo-chaos
    templates:
      - name: custom-chaos
        steps:
          - - name: install-chaos-experiments
              template: install-chaos-experiments
          - - name: pod-memory-hog-yae
              template: pod-memory-hog-yae
          - - name: revert-chaos
              template: revert-chaos
      - name: install-chaos-experiments
        inputs:
          artifacts:
            - name: pod-memory-hog-yae
              path: /tmp/pod-memory-hog-yae.yaml
              raw:
                data: >
                  apiVersion: litmuschaos.io/v1alpha1

                  description:
                    message: |
                      Injects memory consumption on pods belonging to an app deployment
                  kind: ChaosExperiment

                  metadata:
                    name: pod-memory-hog
                    labels:
                      name: pod-memory-hog
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: chaosexperiment
                      app.kubernetes.io/version: 3.0.0-beta5
                  spec:
                    definition:
                      scope: Namespaced
                      permissions:
                        - apiGroups:
                            - ""
                          resources:
                            - pods
                          verbs:
                            - create
                            - delete
                            - get
                            - list
                            - patch
                            - update
                            - deletecollection
                        - apiGroups:
                            - ""
                          resources:
                            - events
                          verbs:
                            - create
                            - get
                            - list
                            - patch
                            - update
                        - apiGroups:
                            - ""
                          resources:
                            - configmaps
                          verbs:
                            - get
                            - list
                        - apiGroups:
                            - ""
                          resources:
                            - pods/log
                          verbs:
                            - get
                            - list
                            - watch
                        - apiGroups:
                            - ""
                          resources:
                            - pods/exec
                          verbs:
                            - get
                            - list
                            - create
                        - apiGroups:
                            - apps
                          resources:
                            - deployments
                            - statefulsets
                            - replicasets
                            - daemonsets
                          verbs:
                            - list
                            - get
                        - apiGroups:
                            - apps.openshift.io
                          resources:
                            - deploymentconfigs
                          verbs:
                            - list
                            - get
                        - apiGroups:
                            - ""
                          resources:
                            - replicationcontrollers
                          verbs:
                            - get
                            - list
                        - apiGroups:
                            - argoproj.io
                          resources:
                            - rollouts
                          verbs:
                            - list
                            - get
                        - apiGroups:
                            - batch
                          resources:
                            - jobs
                          verbs:
                            - create
                            - list
                            - get
                            - delete
                            - deletecollection
                        - apiGroups:
                            - litmuschaos.io
                          resources:
                            - chaosengines
                            - chaosexperiments
                            - chaosresults
                          verbs:
                            - create
                            - list
                            - get
                            - patch
                            - update
                            - delete
                      image: litmuschaos/go-runner:3.0.0-beta5
                      imagePullPolicy: Always
                      args:
                        - -c
                        - ./experiments -name pod-memory-hog
                      command:
                        - /bin/bash
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: MEMORY_CONSUMPTION
                          value: "500"
                        - name: NUMBER_OF_WORKERS
                          value: "1"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                        - name: RAMP_TIME
                          value: ""
                        - name: LIB_IMAGE
                          value: litmuschaos/go-runner:3.0.0-beta5
                        - name: STRESS_IMAGE
                          value: alexeiled/stress-ng:latest-ubuntu
                        - name: CONTAINER_RUNTIME
                          value: containerd
                        - name: SOCKET_PATH
                          value: /run/containerd/containerd.sock
                        - name: SEQUENCE
                          value: parallel
                        - name: TARGET_PODS
                          value: ""
                        - name: NODE_LABEL
                          value: ""
                      labels:
                        name: pod-memory-hog
                        app.kubernetes.io/part-of: litmus
                        app.kubernetes.io/component: experiment-job
                        app.kubernetes.io/runtime-api-usage: "true"
                        app.kubernetes.io/version: 3.0.0-beta5
        container:
          args:
            - kubectl apply -f /tmp/pod-memory-hog-yae.yaml -n
              {{workflow.parameters.adminModeNamespace}} &&  sleep 30
          command:
            - sh
            - -c
          image: litmuschaos/k8s:3.0.0-beta3
      - name: pod-memory-hog-yae
        inputs:
          artifacts:
            - name: pod-memory-hog-yae
              path: /tmp/chaosengine-pod-memory-hog-yae.yaml
              raw:
                data: |
                  apiVersion: litmuschaos.io/v1alpha1
                  kind: ChaosEngine
                  metadata:
                    namespace: "{{workflow.parameters.adminModeNamespace}}"
                    generateName: pod-memory-hog-yae
                    labels:
                      workflow_run_id: "{{workflow.uid}}"
                  spec:
                    engineState: active
                    appinfo:
                      appns: ""
                      applabel: chaosTarget=true
                      appkind: deployment
                    chaosServiceAccount: litmus-admin
                    experiments:
                      - name: pod-memory-hog
                        spec:
                          components:
                            env:
                              - name: TOTAL_CHAOS_DURATION
                                value: "360"
                              - name: MEMORY_CONSUMPTION
                                value: "1000"
                              - name: PODS_AFFECTED_PERC
                                value: ""
                              - name: CONTAINER_RUNTIME
                                value: containerd
                              - name: SOCKET_PATH
                                value: /run/containerd/containerd.sock
                          probe: []
        container:
          args:
            - -file=/tmp/chaosengine-pod-memory-hog-yae.yaml
            - -saveName=/tmp/engine-name
          image: litmuschaos/litmus-checker:3.0.0-beta3
      - name: revert-chaos
        container:
          image: litmuschaos/k8s:3.0.0-beta3
          command:
            - sh
            - -c
          args:
            - kubectl delete chaosengine -l workflow_run_id={{workflow.uid}} -n
              {{workflow.parameters.adminModeNamespace}}
    podGC:
      strategy: OnWorkflowCompletion
  timezone: Europe/Madrid
